version: '2'

services:
  rtl-forwarding:
    image: tnhnclskn/port-forwarding
    ports:
      - 80:80
    volumes:
      - ~/.ssh:/root/.ssh
    environment:
      SRC_ADDR: nat-user.ip
      SRC_PORT: 80
      DST_ADDR: 0.0.0.0
      DST_PORT: 80
      SSH_USER: root
      SSH_ADDR: tunnel-server.ip
      SSH_PORT: 22
  ltr-forwarding:
    image: tnhnclskn/port-forwarding
    volumes:
      - ~/.ssh:/root/.ssh
    environment:
      SRC_ADDR: nat-user.ip
      SRC_PORT: 80
      DST_ADDR: 0.0.0.0
      DST_PORT: 80
      SSH_USER: root
      SSH_ADDR: remote-server.ip
      SSH_PORT: 22
      ROTATE: 'reverse'
